name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=GroceryMarketTests.trx"test --logger "trx;LogFileName=GroceryMarketTests.trx"
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        artifact: /test-results-(.*)/
        name: 'Test report $1'
        path: '/GroceryMarker/GroceryMarketTests/TestResults/net6.0/'
        reporter: 'dotnet'
